# Generated by Django 5.1.6 on 2025-04-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=250)),
                ('sentiment', models.CharField(max_length=17)),
                ('score', models.IntegerField()),
                ('magnitude', models.IntegerField()),
                ('subjectivity', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
