# Generated by Django 5.1.6 on 2025-04-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='magnitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='log',
            name='score',
            field=models.FloatField(),
        ),
    ]
